Repository ESTFE-final/hand_pet, pull requests merged in 2024-10, with the labels that each got.

#32 ADD/ reset, common, button 스타일추가
  src/App.css
  src/App.jsx
  src/Button.jsx
  src/index.css
  src/index.jsx
Labels: documentation

#59 Feature/ 하단-부분-탭-메뉴-그리고-상품-사진-등록페이지-퍼블리싱
  .gitignore
  .prettierrc
  package-lock.json
  src/App.jsx
  src/assets/icons/icon-edit-fill.svg
  src/assets/icons/icon-edit.svg
  src/assets/icons/icon-home-fill.svg
  src/assets/icons/icon-home.svg
  src/assets/icons/icon-message-circle-fill.svg
  src/assets/icons/icon-message-circle.svg
  src/assets/icons/icon-user-fill.svg
  src/assets/icons/icon-user.svg
  src/components/AddProductComponents/FloatinButton.jsx
  src/components/AddProductComponents/GoodsName.jsx
  src/components/AddProductComponents/InputName.jsx
  src/components/AddProductComponents/InputPic.jsx
  src/components/AddProductComponents/InputSell.jsx
  src/components/AddProductComponents/InputTotal.jsx
  src/components/AddProductComponents/SaveButton.jsx
  src/components/TabMenuComponents/TabNavi.jsx
  src/components/TabMenuComponents/keep.jsx
  src/index.jsx
  src/pages/AddProductPage.jsx
  src/pages/MainPage.jsx
  src/pages/ProfilePage.jsx
Labels: documentation, E: 3.0h, high

#73 Revert-Feature/-footer-part-Tap-Menu-and-Goods-picture-RegisterationPage-publishing
  .eslintrc.json
  .gitignore
  .prettierrc
  src/App.jsx
  src/assets/icons/icon-edit-fill.svg
  src/assets/icons/icon-edit.svg
  src/assets/icons/icon-home-fill.svg
  src/assets/icons/icon-home.svg
  src/assets/icons/icon-message-circle-fill.svg
  src/assets/icons/icon-message-circle.svg
  src/assets/icons/icon-user-fill.svg
  src/assets/icons/icon-user.svg
  src/components/AddProductComponents/FloatinButton.jsx
  src/components/AddProductComponents/GoodsName.jsx
  src/components/AddProductComponents/InputName.jsx
  src/components/AddProductComponents/InputPic.jsx
  src/components/AddProductComponents/InputSell.jsx
  src/components/AddProductComponents/InputTotal.jsx
  src/components/AddProductComponents/SaveButton.jsx
  src/components/TabMenuComponents/TabNavi.jsx
  src/components/TabMenuComponents/keep.jsx
  src/index.jsx
  src/pages/AddProductPage.jsx
  src/pages/MainPage.jsx
  src/pages/ProfilePage.jsx
Labels: bug, E: 2.0h, high

#105 72 Features/Load indication, page connection, access restrictions and back to the page function
  src/components/MainComponents/MainProductList.jsx
  src/components/ProfileComponents/Profile.jsx
  src/components/SharedComponents/CommonComponents.jsx
  src/components/TabMenuComponents/TabNavi.jsx
  src/pages/FollowerListPage.jsx
  src/pages/FollowingListPage.jsx
  src/pages/LoginEmailPage.jsx
  src/pages/LoginPage.jsx
  src/pages/NewProfilePage.jsx
  src/pages/ProfilePage.jsx
  src/pages/SignUpPage.jsx
  src/pages/SplashScreenPage.jsx
Labels: documentation, E: 3.0h, high
